# 下载路径直接写到你的家目录
dir=/home/usfese/Downloads

# 冲突的 RPC 端口
rpc-listen-port=6800
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true

# 建议添加一个 session 保持文件，否则未下载完的任务重启后会丢失
input-file=/home/usfese/.config/aria2/aria2.session
save-session=/home/usfese/.config/aria2/aria2.session
all-proxy=http://127.0.0.1:7890
