# =====================
# 🎬 Mode Switch
# =====================
# F1 script-message-to manual-mode mode-anime
# F2 script-message-to manual-mode mode-upscale
# F3 script-message-to manual-mode mode-cinema
# F4 script-message-to manual-mode mode-auto

# =====================
# ⏭ OP / ED
# =====================
Ctrl+o script-message skip-op
Ctrl+e script-message skip-ed

# =====================
# ⏩ Seek
# =====================
RIGHT seek 5
LEFT seek -5
Alt+RIGHT seek 10
Alt+LEFT seek -10

# =====================
# 🎧 Audio
# =====================
a cycle audio
s cycle-values af "dynaudnorm" ""

# =====================
# 🎞 Shader toggle（可选）
# =====================
z cycle glsl-shaders
F5 show-text "Pure mode" ; apply-profile pure
z cycle glsl-shaders
x set glsl-shaders ""
Ctrl+s script-message generate-sub
