cursor              #9dd49e
cursor_text_color  #263333
foreground            #d7e5e5
background            #091516
selection_foreground  #023913
selection_background  #9dd49e
url_color             #89d98f

# black
color8   #7b9696
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (优化为更舒适清晰的鼠尾草灰绿)
color2   #9ab38d
color10  #b0c9a3

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #89d98f
color12 #a39ec4

# magenta
color5   #80d4d7
color13  #9cf1f3

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #9dd49e
color14  #9dd49e

# white
color15  #e7e7e7
color7   #f0f0f0
